# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100O8IZKH4AnuqXOpzTCawOztq3yXPgw_
"""

import time

def phishing_training():
    print("\nPhishing Awareness Training\n")
    print("Learn how to recognize and avoid phishing emails, websites, and social engineering tactics.\n")
    time.sleep(1)

    print("What is Phishing?\n")
    print("Phishing is a cyber-attack where scammers trick you into giving personal information.\n")
    print("Common Tactics:")
    print("1. Email Phishing - Fake emails pretending to be from legitimate sources.")
    print("2. Vishing - Phone scams asking for sensitive information.")
    print("3. Smishing - Fraudulent SMS messages.")
    print("4. Website Spoofing - Fake websites imitating real ones.")
    print("5. Social Engineering - Manipulating people into giving confidential data.\n")
    time.sleep(2)

    print("How to Avoid Phishing Emails:")
    print("- Check for spelling errors and generic greetings.")
    print("- Never click on suspicious links or download unknown attachments.")
    print("- Verify the sender's email address carefully.\n")
    time.sleep(2)

    print("How to Avoid Fake Websites:")
    print("- Look for HTTPS and a secure lock icon in the URL.")
    print("- Avoid clicking links in unsolicited emails.")
    print("- Type the website URL directly into the browser instead of using provided links.\n")
    time.sleep(2)

    print("How to Avoid Social Engineering Scams:")
    print("- Be cautious of urgent or fear-inducing messages.")
    print("- Verify the request by contacting the organization directly.")
    print("- Do not share sensitive information over the phone or email unless verified.\n")
    time.sleep(2)

    quiz()

def quiz():
    print("Quiz: Spot the Phishing Attempt\n")
    print("Which of these is a phishing attempt?")
    print("A: An email from your bank asking you to update your password via a link.")
    print("B: A confirmation email from an online purchase you made.\n")

    answer = input("Enter your choice (A/B): ").strip().upper()

    if answer == 'A':
        print("Correct! This is a common phishing tactic.")
    elif answer == 'B':
        print("Incorrect. Be cautious of unexpected email links!")
    else:
        print("Invalid choice. Please enter A or B.")
        quiz()

if __name__ == "__main__":
    phishing_training()